"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'flnh=1!tsz^4&grtw&0$2&6#n*@aybhg-vdpa-i1rc&pyv$+9c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

if DEBUG is True:
	with open("/code/logs/debug.log", "a+") as ff:
		for a in os.environ:
			ff.write("{}{}{}{}".format('Var: ', str(a), 'Value: ', str(os.getenv(a))))
			ff.write("\n")

# Application definition

INSTALLED_APPS = [
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',

	'mysite.core',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [
			os.path.join(BASE_DIR, 'mysite/templates')
		],
		'APP_DIRS': True,
		'OPTIONS': {
				'context_processors': [
						'django.template.context_processors.debug',
						'django.template.context_processors.request',
						'django.contrib.auth.context_processors.auth',
						'django.contrib.messages.context_processors.messages',
				],
		},
	},
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': 'postgres',
		'USER': 'sujan',
		'PASSWORD': '9680',
		'HOST': 'db',
		'PORT': 5432,
		# 'PORT': '7456',
	}
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'


CELERY_BROKER_URL = 'amqp://broker'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

LOG_FILE_PATH = '/code/logs/mysite.log'

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'formatters': {
		'standard': {
			'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
		},
	},
	'handlers': {
		'default': {
			'level': 'INFO',
			'formatter': 'standard',
			'class': 'logging.FileHandler',
			'filename': LOG_FILE_PATH
		},
		'adminhandler': {  # NOTE: THIS IS NOT USED
			'level': 'WARN',
			'formatter': 'standard',
			'class': 'logging.handlers.SMTPHandler',
			'mailhost': '',  # NOTE: add value here
			'fromaddr': 'admin@gmail.com',
			'toaddrs': ['system@gmail.com'],
			'subject': 'Warning/Error Log'
		}
	},
	'loggers': {
		'': {
			'handlers': ['default'],
			'level': 'INFO',
			'propagate': False
		},
		'django.request': {
			'handlers': ['default'],
			'level': 'WARN',
			'propagate': False
		},
		'adminlogger': {  # NOTE: THIS IS NOT USED
			'handlers': ['adminhandler'],
			'level': 'WARN',
			'propagate': False
		}
	}
}