name: Banco CI

on:
  push:
    branches: [ master ]

jobs:
  job1:
    build:

      runs-on: [self-hosted]

      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          
          repository: sujansharma07/django-celery-example
          tags: |
            ghcr.io/sujansharma07/django-celery-example:${{ github.run_number }}
            ghcr.io/sujansharma07/django-celery-example:latest
          #push: ${{ github.ref == 'refs/heads/main' }}
          push: true
  job2:
    needs: job1
    steps:
    - name: Deploy
      uses: actions/checkout@v2
    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}

