name: Banco CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    # name: Job 1

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        
        repository: ${{ secrets.GHCR_USERNAME }}/${{ secrets.PROJ_NAME }}
        tags: |
          ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ secrets.PROJ_NAME }}:${{ github.run_number }}
          ghcr.io/${{ secrets.GHCR_USERNAME }}/${{ secrets.PROJ_NAME }}:latest
        #push: ${{ github.ref == 'refs/heads/main' }}
        push: true


  intermediate:
    # name: Job 2
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Dependant is Running
      run: |
        echo "Completed intermediate and triggering deploy"

  deploy:
    
    runs-on: [self-hosted]

    needs: intermediate
    
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{secrets.SSH_PRIVATE_KEY}} 
        known_hosts: 'SSH KEY'
        if_key_exists: replace

    - name: Adding Known Hosts
      run: |
        ssh-keyscan -H ${{secrets.SERVER}} >> ~/.ssh/known_hosts
    
    - name: Copy required files to server
      run: |
        rsync -avzP --include "docker-compose.yml" --include ".env" --include "nginx/***" \
          --exclude "*" ./ root@${{secrets.SERVER}}:/opt/${{env.PROJECT_NAME}}/
        ssh root@${{secrets.SERVER}} "cd /opt/${{env.PROJECT_NAME}} && /usr/bin/docker-compose -f docker-compose.yml down && \
          /usr/bin/docker-compose -f docker-compose.yml up -d"
    
    