name: Banco CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    # name: Job 1

    runs-on: [self-hosted]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        
        repository: sujansharma07/docker-celery-postgresql-rabbitmq-django
        tags: |
          ghcr.io/sujansharma07/docker-celery-postgresql-rabbitmq-django:${{ github.run_number }}
          ghcr.io/sujansharma07/docker-celery-postgresql-rabbitmq-django:latest
        #push: ${{ github.ref == 'refs/heads/main' }}
        push: true


  intermediate:
    # name: Job 2
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Dependant is Running
      run: |
        echo "Completed intermediate and triggering deploy"

  deploy:
    
    runs-on: [self-hosted]

    needs: intermediate
    
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{secrets.SSH_PRIVATE_KEY}} 
        known_hosts: 'SSH KEY'
        if_key_exists: replace

    - name: Adding Known Hosts
      run: |
        ssh-keyscan -H ${{secrets.SERVER}} >> ~/.ssh/known_hosts
    
    - name: Copy required files to server
      run: |
        rsync -avzP --include "docker-compose.yml" \
          --exclude "*" ./ ubuntu@${{secrets.SERVER}}:/opt/swarm_project/
        ssh ubuntu@${{secrets.SERVER}} "cd /opt/swarm_project && export GHCR_PAT="${{secrets.GHCR_PAT}}" && \ 
        echo $GHCR_PAT | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin && docker stack deploy --compose-file=/opt/swarm_project/docker-compose.yml ${{ secrets.PROJ_NAME }} && \ 
        docker service scale ${{ secrets.PROJ_NAME }}=2"
    
    # To remove staack from swarm: docker stack rm docker-celery-postgresql-rabbitmq-django














# rsync -avzP --include "docker-compose-prod.yml" --include "nginx/***" \
#   --exclude "*" ./ root@${{secrets.SERVER}}:/opt/${{env.PROJECT_NAME}}/
# ssh root@${{secrets.SERVER}} "cd /opt/${{env.PROJECT_NAME}} && /usr/bin/docker-compose -f docker-compose-prod.yml down && \
#   /usr/bin/docker-compose -f docker-compose-prod.yml up -d"